export const allResData = [
  {
    name: 'KFC',
    cuisine: 'Burgers, Fried Chicken, Beverages',
    rating: 4.4,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxRmYX4OqLGoOrbQXe2XFcDAbNphmu7dgkdQ&s',
  },
  {
    name: "Domino's Pizza",
    cuisine: 'Pizza, Pasta, Garlic Bread',
    rating: 4.2,
    img: 'https://www.dominos.co.in/files/items/_1346164951.jpg',
  },
  {
    name: 'Subway',
    cuisine: 'Sandwiches, Salads, Beverages',
    rating: 4.1,
    img: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/12/3ec41225-1b07-4a3b-a824-65607702b001_57445.jpg',
  },
  {
    name: 'Starbucks',
    cuisine: 'Coffee, Desserts, Snacks',
    rating: 4.5,
    img: 'https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/RX_THUMBNAIL/IMAGES/VENDOR/2025/3/17/613df62a-0363-4d0c-9d14-e1b91e018461_326482.JPG',
  },
  {
    name: 'Burger King',
    cuisine: 'Burgers, Fries, Shakes',
    rating: 4.3,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-Mu-Hazrk59tg-aJpPwMsdpQ5MkkOwC7tbQ&s',
  },
  {
    name: 'Taco Bell',
    cuisine: 'Tacos, Burritos, Nachos',
    rating: 4.0,
    img: 'https://content.jdmagicbox.com/comp/def_content_category/taco-bell-11979003-giedz74byz-250.jpg',
  },
  {
    name: "McDonald's",
    cuisine: 'Burgers, Fries, Soft Drinks',
    rating: 4.2,
    img: 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_366/RX_THUMBNAIL/IMAGES/VENDOR/2025/6/3/0091bc52-b0bb-4b6d-86c5-30a83e9aaf91_57241.jpg',
  },
  {
    name: 'Pizza Hut',
    cuisine: 'Pizza, Pasta, Desserts',
    rating: 4.1,
    img: 'https://www.yum.com/wps/wcm/connect/yumbrands/77ac5d27-1357-4792-9953-54b11f5ae7dd/yum-com-24-product-PH.jpg?MOD=AJPERES&CACHEID=ROOTWORKSPACE.Z18_5QC4HBC039RJ406SQH4UBH3695-77ac5d27-1357-4792-9953-54b11f5ae7dd-oXSxcXb',
  },
  {
    name: 'Cafe Coffee Day',
    cuisine: 'Coffee, Sandwiches, Pastries',
    rating: 4.0,
    img: 'https://b.zmtcdn.com/data/pictures/chains/1/95011/f956ddd8f1f2536e2fcbaaf526e95426.jpg',
  },
  {
    name: 'Baskin Robbins',
    cuisine: 'Ice Cream, Sundaes, Beverages',
    rating: 4.6,
    img: 'https://b.zmtcdn.com/data/pictures/chains/3/95463/a806cca22bb4d73d7d7a9014cb653f09.jpg?fit=around|960:500&crop=960:500;*,*',
  },
];

//////////////////////////////////////////////////////////////
export const restaurantDetails = [
  {
    id: 1,
    name: 'KFC',
    cusines: ['Burgers', 'Fried Chicken', 'Beverages'],
    costForTwo: 500,
    delivery: 30,
    menu: [
      { item: 'Zinger Burger', price: 199 },
      { item: 'Hot Wings (6 pcs)', price: 249 },
      { item: 'Pepsi (500ml)', price: 50 },
    ],
  },
  {
    id: 2,
    name: "Domino's Pizza",
    cusines: ['Pizza', 'Pasta', 'Garlic Bread'],
    costForTwo: 600,
    delivery: 25,
    menu: [
      { item: 'Veg Extravaganza', price: 349 },
      { item: 'Garlic Breadsticks', price: 129 },
      { item: 'Choco Lava Cake', price: 99 },
    ],
  },
  {
    id: 3,
    name: 'Subway',
    cusines: ['Sandwiches', 'Salads', 'Beverages'],
    costForTwo: 450,
    delivery: 20,
    menu: [
      { item: 'Paneer Tikka Sub', price: 180 },
      { item: 'Veggie Delight Salad', price: 150 },
      { item: 'Iced Tea', price: 60 },
    ],
  },
  {
    id: 4,
    name: 'Starbucks',
    cusines: ['Coffee', 'Desserts', 'Snacks'],
    costForTwo: 700,
    delivery: 35,
    menu: [
      { item: 'Caffè Latte', price: 240 },
      { item: 'Blueberry Muffin', price: 180 },
      { item: 'Chocolate Croissant', price: 150 },
    ],
  },
  {
    id: 5,
    name: 'Burger King',
    cusines: ['Burgers', 'Fries', 'Shakes'],
    costForTwo: 500,
    delivery: 25,
    menu: [
      { item: 'Whopper', price: 230 },
      { item: 'Peri Peri Fries', price: 90 },
      { item: 'Choco Shake', price: 110 },
    ],
  },
  {
    id: 6,
    name: 'Taco Bell',
    cusines: ['Tacos', 'Burritos', 'Nachos'],
    costForTwo: 400,
    delivery: 20,
    menu: [
      { item: 'Crunchy Taco', price: 120 },
      { item: 'Veg Burrito', price: 180 },
      { item: 'Cheesy Nachos', price: 130 },
    ],
  },
  {
    id: 7,
    name: "McDonald's",
    cusines: ['Burgers', 'Fries', 'Soft Drinks'],
    costForTwo: 450,
    delivery: 30,
    menu: [
      { item: 'McAloo Tikki Burger', price: 60 },
      { item: 'Large Fries', price: 110 },
      { item: 'Coke Float', price: 90 },
    ],
  },
  {
    id: 8,
    name: 'Pizza Hut',
    cusines: ['Pizza', 'Pasta', 'Desserts'],
    costForTwo: 550,
    delivery: 25,
    menu: [
      { item: 'Tandoori Paneer Pizza', price: 299 },
      { item: 'Cheesy Pasta', price: 170 },
      { item: 'Brownie with Ice Cream', price: 130 },
    ],
  },
  {
    id: 9,
    name: 'Cafe Coffee Day',
    cusines: ['Coffee', 'Sandwiches', 'Pastries'],
    costForTwo: 400,
    delivery: 20,
    menu: [
      { item: 'Cappuccino', price: 160 },
      { item: 'Paneer Sandwich', price: 140 },
      { item: 'Black Forest Pastry', price: 100 },
    ],
  },
  {
    id: 10,
    name: 'Baskin Robbins',
    cusines: ['Ice Cream', 'Sundaes', 'Beverages'],
    costForTwo: 350,
    delivery: 15,
    menu: [
      { item: 'Honey Nut Crunch Scoop', price: 120 },
      { item: 'Chocolate Sundae', price: 160 },
      { item: 'Mango Milkshake', price: 110 },
    ],
  },
];
